<x-app-layout>
<x-slot name="title">Regeneration Log #{{ $log->id }}</x-slot>
<x-alert />

@push('styles')
<style>
.diff-row-changed { background: #fff8e1; }
.diff-row-increased td { color: #198754; }
.diff-row-decreased td { color: #dc3545; }
.snapshot-table th { font-size: .78rem; text-transform: uppercase; letter-spacing: .04em; color: #888; }
.snapshot-table td { font-size: .85rem; }
</style>
@endpush

{{-- ── Header ───────────────────────────────────────────────────────── --}}
<div class="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-2">
    <div>
        <h5 class="fw-bold mb-0">
            <i class="bi bi-clock-history me-2 text-secondary"></i>
            Regeneration Log #{{ $log->id }}
        </h5>
        <small class="text-muted">
            {{ $log->employee?->full_name ?? '—' }} — {{ $log->month_label }}
        </small>
    </div>
    <div class="d-flex gap-2">
        @if($log->payroll_id)
        <a href="{{ route('payroll.show', $log->payroll_id) }}" class="btn btn-outline-primary btn-sm">
            <i class="bi bi-receipt me-1"></i> View Current Payroll
        </a>
        @endif
        <a href="{{ route('payroll-regeneration.logs') }}" class="btn btn-outline-secondary btn-sm">
            <i class="bi bi-arrow-left me-1"></i> Back to Log
        </a>
    </div>
</div>

{{-- ── Meta card ────────────────────────────────────────────────────── --}}
<div class="hrms-card p-4 mb-4">
    <div class="row g-3">
        <div class="col-sm-4">
            <small class="text-muted d-block">Employee</small>
            <span class="fw-semibold">{{ $log->employee?->full_name ?? '—' }}</span>
        </div>
        <div class="col-sm-2">
            <small class="text-muted d-block">Period</small>
            <span class="fw-semibold">{{ $log->month_label }}</span>
        </div>
        <div class="col-sm-2">
            <small class="text-muted d-block">Type</small>
            @if($log->was_locked)
                <span class="badge bg-danger">Locked Override</span>
            @else
                <span class="badge bg-secondary">Draft Regen</span>
            @endif
        </div>
        <div class="col-sm-2">
            <small class="text-muted d-block">Regenerated By</small>
            <span class="fw-semibold">{{ $log->regeneratedBy?->name ?? '—' }}</span>
        </div>
        <div class="col-sm-2">
            <small class="text-muted d-block">Date</small>
            <span class="fw-semibold">{{ $log->created_at->format('M j, Y H:i') }}</span>
        </div>
        @if($log->reason)
        <div class="col-12">
            <small class="text-muted d-block">Reason</small>
            <p class="mb-0 fw-semibold text-warning-emphasis">{{ $log->reason }}</p>
        </div>
        @endif
    </div>
</div>

{{-- ── Side-by-side diff ────────────────────────────────────────────── --}}
@php
$fields = [
    'base_salary'       => 'Base Salary',
    'bonus'             => 'Bonus',
    'incentive'         => 'Incentive',
    'overtime_amount'   => 'Overtime',
    'gross_salary'      => 'Gross Salary',
    'late_deduction'    => 'Late Deduction',
    'absent_deduction'  => 'Absent Deduction',
    'leave_deduction'   => 'Leave Deduction',
    'total_deductions'  => 'Total Deductions',
    'net_salary'        => 'Net Salary',
    'working_days'      => 'Working Days',
    'present_days'      => 'Present Days',
    'late_days'         => 'Late Days',
    'absent_days'       => 'Absent Days',
    'unpaid_leave_days' => 'Unpaid Leave',
    'paid_leave_days'   => 'Paid Leave',
    'status'            => 'Status',
];
$old = $log->old_snapshot ?? [];
$new = $log->new_snapshot ?? [];
$currencyFields = ['base_salary','bonus','incentive','overtime_amount','gross_salary',
                   'late_deduction','absent_deduction','leave_deduction','total_deductions','net_salary'];
@endphp

<div class="hrms-card">
    <div class="card-header fw-semibold">
        <i class="bi bi-arrow-left-right me-2"></i>Before vs After
    </div>
    <div class="table-responsive">
        <table class="table table-bordered snapshot-table mb-0">
            <thead class="table-light">
                <tr>
                    <th style="width:25%">Field</th>
                    <th style="width:32%">Before (Old)</th>
                    <th style="width:32%">After (New)</th>
                    <th>Δ</th>
                </tr>
            </thead>
            <tbody>
                @foreach($fields as $key => $label)
                @php
                    $oldVal = $old[$key] ?? null;
                    $newVal = $new[$key] ?? null;
                    $changed = $oldVal != $newVal;
                    $isCurrency = in_array($key, $currencyFields);
                    $delta = null;
                    $deltaClass = '';
                    if ($isCurrency && $oldVal !== null && $newVal !== null) {
                        $delta = (float)$newVal - (float)$oldVal;
                        if ($delta > 0) $deltaClass = 'text-success fw-semibold';
                        elseif ($delta < 0) $deltaClass = 'text-danger fw-semibold';
                    }
                    $rowClass = $changed ? 'diff-row-changed' : '';
                @endphp
                <tr class="{{ $rowClass }}">
                    <td class="text-muted">{{ $label }}</td>
                    <td>
                        @if($oldVal !== null)
                            @if($isCurrency) {{ currency($oldVal) }}
                            @else {{ $oldVal }}
                            @endif
                        @else <span class="text-muted">—</span>
                        @endif
                    </td>
                    <td>
                        @if($newVal !== null)
                            @if($isCurrency) {{ currency($newVal) }}
                            @else {{ $newVal }}
                            @endif
                        @else <span class="text-muted">—</span>
                        @endif
                    </td>
                    <td>
                        @if($delta !== null)
                            @if($delta != 0)
                                <span class="{{ $deltaClass }}">
                                    {{ $delta > 0 ? '+' : '' }}{{ currency($delta) }}
                                </span>
                            @else
                                <span class="text-muted" style="font-size:.78rem;">no change</span>
                            @endif
                        @elseif($changed)
                            <span class="text-warning" style="font-size:.78rem;">changed</span>
                        @else
                            <span class="text-muted">—</span>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

</x-app-layout>
