<x-app-layout>
<x-slot name="title">Payroll Regeneration Audit Log</x-slot>
<x-alert />

{{-- ── Page Header ──────────────────────────────────────────────────── --}}
<div class="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-2">
    <div>
        <h5 class="fw-bold mb-0"><i class="bi bi-clock-history me-2 text-secondary"></i>Regeneration Audit Log</h5>
        <small class="text-muted">Full history of all payroll regeneration actions.</small>
    </div>
    @can('create', \App\Models\PayrollRegenerationLog::class)
    <a href="{{ route('payroll-regeneration.index') }}" class="btn btn-warning btn-sm">
        <i class="bi bi-arrow-repeat me-1"></i> Regenerate Payroll
    </a>
    @endcan
</div>

<div class="hrms-card">
    <div class="p-0">
        @if($logs->isEmpty())
            <p class="text-muted text-center py-5 mb-0">No regeneration records found.</p>
        @else
        <div class="table-responsive">
            <table class="table table-hover mb-0">
                <thead class="table-light">
                    <tr>
                        <th>#</th>
                        <th>Employee</th>
                        <th>Period</th>
                        <th>Type</th>
                        <th>Old Net</th>
                        <th>New Net</th>
                        <th>Δ Net</th>
                        <th>Reason</th>
                        <th>Regenerated By</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($logs as $log)
                    @php
                        $oldNet = $log->old_snapshot['net_salary'] ?? null;
                        $newNet = $log->new_snapshot['net_salary'] ?? null;
                        $delta  = ($oldNet !== null && $newNet !== null) ? ($newNet - $oldNet) : null;
                    @endphp
                    <tr>
                        <td class="text-muted" style="font-size:.8rem;">{{ $log->id }}</td>
                        <td>
                            <a href="{{ route('employees.show', $log->employee_id) }}" class="text-decoration-none fw-semibold">
                                {{ $log->employee?->full_name ?? '—' }}
                            </a>
                        </td>
                        <td>{{ $log->month_label }}</td>
                        <td>
                            @if($log->was_locked)
                                <span class="badge bg-danger-subtle text-danger">
                                    <i class="bi bi-lock me-1"></i>Locked Override
                                </span>
                            @else
                                <span class="badge bg-secondary-subtle text-secondary">Draft Regen</span>
                            @endif
                        </td>
                        <td class="text-muted">{{ $oldNet !== null ? currency($oldNet) : '—' }}</td>
                        <td class="fw-semibold">{{ $newNet !== null ? currency($newNet) : '—' }}</td>
                        <td>
                            @if($delta !== null)
                                @if($delta > 0)
                                    <span class="text-success fw-semibold">+{{ currency($delta) }}</span>
                                @elseif($delta < 0)
                                    <span class="text-danger fw-semibold">{{ currency($delta) }}</span>
                                @else
                                    <span class="text-muted">No change</span>
                                @endif
                            @else
                                —
                            @endif
                        </td>
                        <td class="text-muted" style="font-size:.82rem;">
                            {{ $log->reason ? \Str::limit($log->reason, 50) : '—' }}
                        </td>
                        <td>{{ $log->regeneratedBy?->name ?? '—' }}</td>
                        <td style="font-size:.82rem;">{{ $log->created_at->format('M j, Y H:i') }}</td>
                        <td>
                            <a href="{{ route('payroll-regeneration.log-show', $log) }}"
                               class="btn btn-sm btn-outline-secondary">
                                <i class="bi bi-eye"></i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        @if($logs->hasPages())
        <div class="px-4 py-3">{{ $logs->links() }}</div>
        @endif
        @endif
    </div>
</div>

</x-app-layout>
