<x-app-layout>
    <x-slot name="title">Review Registration</x-slot>

    @if(session('success'))
    <div class="alert alert-success alert-dismissible fade show mb-4" role="alert">
        <i class="bi bi-check-circle me-2"></i>{{ session('success') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    @endif
    @if(session('error'))
    <div class="alert alert-danger alert-dismissible fade show mb-4" role="alert">
        <i class="bi bi-exclamation-triangle me-2"></i>{{ session('error') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    @endif

    {{-- ── Page header ──────────────────────────────────────────────── --}}
    <div class="d-flex justify-content-between align-items-center mb-3">
        <div>
            <h5 class="fw-bold mb-0">Review Registration</h5>
            <small class="text-muted">
                Submitted {{ $registration->created_at->format('d M Y H:i') }}
            </small>
        </div>
        <a href="{{ route('registrations.index') }}" class="btn btn-outline-secondary btn-sm">
            <i class="bi bi-arrow-left me-1"></i> Back
        </a>
    </div>

    {{-- ── Inviter label banner ──────────────────────────────────── --}}
    @php $inviter = $registration->invitation?->creator; @endphp
    <div class="alert alert-primary d-flex align-items-center gap-3 mb-4 py-2" style="font-size:.875rem;">
        <i class="bi bi-person-badge fs-5 flex-shrink-0"></i>
        <div>
            <span class="fw-semibold">Registered via link generated by {{ $inviter?->name ?? 'Unknown' }}</span>
            @if($registration->invitation?->note)
            &nbsp;·&nbsp;<span class="text-muted">{{ $registration->invitation->note }}</span>
            @endif
            <div class="text-muted" style="font-size:.78rem;margin-top:1px;">
                Link used {{ $registration->invitation?->uses_count ?? '—' }}
                / {{ $registration->invitation?->max_uses === null ? '∞' : $registration->invitation->max_uses }} times
                &nbsp;·&nbsp;
                Link {{ $registration->invitation?->status ?? '—' }}
            </div>
        </div>
    </div>

    @php
        $isPending            = $registration->status === 'pending';
        $isCorrection         = $registration->status === 'correction_required';
        $isEditable           = $isPending || $isCorrection;
        $canApprove           = $isPending || $isCorrection;   // HR can approve either state
    @endphp

    {{-- ── Correction required banner ─────────────────────────────── --}}
    @if($isCorrection)
    <div class="alert alert-warning d-flex align-items-start gap-3 mb-4">
        <i class="bi bi-exclamation-triangle-fill fs-5 flex-shrink-0 mt-1"></i>
        <div>
            <strong>Correction Required</strong>
            <div class="mt-1">{{ $registration->correction_note }}</div>
            <small class="text-muted">
                Requested by {{ $registration->reviewer?->name ?? '—' }}
                on {{ $registration->reviewed_at?->format('d M Y H:i') ?? '—' }}
            </small>
        </div>
    </div>
    @endif

    {{-- ── Approved / Rejected banner ──────────────────────────────── --}}
    @if(! $isEditable && $registration->status !== 'correction_required')
    <div class="alert {{ $registration->status === 'approved' ? 'alert-success' : 'alert-danger' }} mb-4">
        <strong>{{ ucfirst($registration->status) }}</strong>
        by {{ $registration->reviewer?->name ?? '—' }}
        on {{ $registration->reviewed_at?->format('d M Y H:i') ?? '—' }}
        @if($registration->rejection_note)
        <br><em>Note: {{ $registration->rejection_note }}</em>
        @endif
        @if($registration->employee)
        — <a href="{{ route('employees.show', $registration->employee) }}" class="alert-link">View Employee Profile</a>
        @endif
    </div>
    @endif

    {{-- The form action is switched by JS when "Save & Approve" is clicked --}}
    <form method="POST" id="mainRegistrationForm"
          action="{{ route('registrations.update', $registration) }}"
          enctype="multipart/form-data">
        @csrf @method('PATCH')
        {{-- Hidden flag — toggled to POST by Save & Approve button --}}
        <input type="hidden" id="formActionOverride" value="">

        <div class="row g-4">
            <div class="col-lg-8">

                {{-- ── Profile Photo + Personal Info ───────────────── --}}
                <div class="hrms-card p-4 mb-4">
                    <h6 class="fw-semibold mb-3 text-muted text-uppercase" style="font-size:.72rem;letter-spacing:.05em;">
                        Personal Information
                    </h6>

                    {{-- Photo row --}}
                    <div class="d-flex align-items-start gap-4 mb-4">
                        <div>
                            @if($registration->photo_url)
                            <img src="{{ $registration->photo_url }}" alt="Profile photo"
                                 style="width:90px;height:90px;border-radius:50%;object-fit:cover;border:3px solid #e9ecef;">
                            @else
                            <div style="width:90px;height:90px;border-radius:50%;background:#e9ecef;display:flex;align-items:center;justify-content:center;border:3px solid #dee2e6;">
                                <i class="bi bi-person-fill fs-2 text-secondary"></i>
                            </div>
                            @endif
                            @if($isEditable)
                            <div class="mt-2 text-center">
                                <label for="photoUpdateInput" class="btn btn-outline-secondary btn-sm" style="font-size:.73rem;">
                                    <i class="bi bi-camera me-1"></i>Change
                                </label>
                                <input type="file" name="photo" id="photoUpdateInput" class="d-none"
                                       accept="image/jpeg,image/png,image/jpg"
                                       onchange="previewUpdatePhoto(this)">
                            </div>
                            @endif
                        </div>
                        <div class="flex-grow-1">
                            <div class="fw-semibold fs-5">{{ $registration->full_name }}</div>
                            <div class="text-muted" style="font-size:.875rem;">{{ $registration->email }}</div>
                            @if($registration->login_id)
                            <div class="mt-1">
                                <span class="badge bg-secondary-subtle text-secondary border border-secondary-subtle">
                                    <i class="bi bi-at me-1"></i>{{ $registration->login_id }}
                                </span>
                            </div>
                            @endif
                        </div>
                    </div>

                    <div class="row g-3">
                        <div class="col-md-6">
                            <label class="form-label">First Name <span class="text-danger">*</span></label>
                            <input type="text" name="first_name"
                                   class="form-control @error('first_name') is-invalid @enderror"
                                   value="{{ old('first_name', $registration->first_name) }}"
                                   {{ $isEditable ? '' : 'readonly' }} required>
                            @error('first_name')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">Last Name <span class="text-danger">*</span></label>
                            <input type="text" name="last_name"
                                   class="form-control @error('last_name') is-invalid @enderror"
                                   value="{{ old('last_name', $registration->last_name) }}"
                                   {{ $isEditable ? '' : 'readonly' }} required>
                            @error('last_name')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">Email <span class="text-danger">*</span></label>
                            <input type="email" name="email"
                                   class="form-control @error('email') is-invalid @enderror"
                                   value="{{ old('email', $registration->email) }}"
                                   {{ $isEditable ? '' : 'readonly' }} required>
                            <div class="form-text">Used for login, notifications, and Time Doctor matching.</div>
                            @error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">Employee Code <small class="text-muted">(organization)</small></label>
                            <input type="text" name="organization_employee_code"
                                   class="form-control @error('organization_employee_code') is-invalid @enderror"
                                   value="{{ old('organization_employee_code', $registration->organization_employee_code) }}"
                                   {{ $isEditable ? '' : 'readonly' }}
                                   placeholder="Optional company-provided code">
                            @error('organization_employee_code')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">Phone</label>
                            <input type="text" name="phone"
                                   class="form-control @error('phone') is-invalid @enderror"
                                   value="{{ old('phone', $registration->phone) }}"
                                   {{ $isEditable ? '' : 'readonly' }}>
                            @error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">Date of Birth</label>
                            <input type="date" name="date_of_birth"
                                   class="form-control @error('date_of_birth') is-invalid @enderror"
                                   value="{{ old('date_of_birth', $registration->date_of_birth?->format('Y-m-d')) }}"
                                   {{ $isEditable ? '' : 'readonly' }}>
                            @error('date_of_birth')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">Gender</label>
                            @if($isEditable)
                            <select name="gender" class="form-select @error('gender') is-invalid @enderror">
                                <option value="">— Select —</option>
                                <option value="male"   {{ old('gender', $registration->gender) === 'male'   ? 'selected' : '' }}>Male</option>
                                <option value="female" {{ old('gender', $registration->gender) === 'female' ? 'selected' : '' }}>Female</option>
                                <option value="other"  {{ old('gender', $registration->gender) === 'other'  ? 'selected' : '' }}>Other</option>
                            </select>
                            @else
                            <input type="text" class="form-control" value="{{ ucfirst($registration->gender ?? '—') }}" readonly>
                            @endif
                            @error('gender')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                        <div class="col-12">
                            <label class="form-label">Address</label>
                            <input type="text" name="address"
                                   class="form-control @error('address') is-invalid @enderror"
                                   value="{{ old('address', $registration->address) }}"
                                   {{ $isEditable ? '' : 'readonly' }}>
                            @error('address')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                    </div>
                </div>

                {{-- ── NID & Documents ──────────────────────────────── --}}
                <div class="hrms-card p-4 mb-4">
                    <h6 class="fw-semibold mb-3 text-muted text-uppercase" style="font-size:.72rem;letter-spacing:.05em;">
                        Identity &amp; Documents
                    </h6>
                    <div class="row g-3">
                        <div class="col-md-6">
                            <label class="form-label">NID Number</label>
                            <input type="text" name="nid"
                                   class="form-control @error('nid') is-invalid @enderror"
                                   value="{{ old('nid', $registration->nid) }}"
                                   {{ $isEditable ? '' : 'readonly' }} maxlength="50">
                            @error('nid')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>

                        <div class="col-md-6">
                            <label class="form-label">NID Document</label>
                            @if($registration->nid_document)
                            <div class="mb-1">
                                <a href="{{ asset('storage/'.$registration->nid_document) }}" target="_blank"
                                   class="btn btn-outline-danger btn-sm">
                                    <i class="bi bi-file-earmark-pdf me-1"></i>View NID Document
                                </a>
                            </div>
                            @endif
                            @if($isEditable)
                            <input type="file" name="nid_document"
                                   class="form-control @error('nid_document') is-invalid @enderror"
                                   accept="application/pdf">
                            <small class="text-muted">PDF only, max 5MB. Leave blank to keep existing.</small>
                            @error('nid_document')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            @elseif(!$registration->nid_document)
                            <span class="text-muted">—</span>
                            @endif
                        </div>

                        <div class="col-md-6">
                            <label class="form-label">Education Certificate</label>
                            @if($registration->certificate)
                            <div class="mb-1">
                                <a href="{{ asset('storage/'.$registration->certificate) }}" target="_blank"
                                   class="btn btn-outline-primary btn-sm">
                                    <i class="bi bi-file-earmark-text me-1"></i>View Certificate
                                </a>
                            </div>
                            @endif
                            @if($isEditable)
                            <input type="file" name="certificate"
                                   class="form-control @error('certificate') is-invalid @enderror"
                                   accept="application/pdf">
                            <small class="text-muted">PDF only, max 5MB. Leave blank to keep existing.</small>
                            @error('certificate')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            @elseif(!$registration->certificate)
                            <span class="text-muted">—</span>
                            @endif
                        </div>

                        <div class="col-md-6">
                            <label class="form-label">Login ID</label>
                            @if($isEditable)
                            <input type="text" name="login_id"
                                   class="form-control @error('login_id') is-invalid @enderror"
                                   value="{{ old('login_id', $registration->login_id) }}"
                                   minlength="4" maxlength="50" pattern="[a-zA-Z0-9_]+" required>
                            <small class="text-muted">Alphanumeric + underscore, min 4 chars.</small>
                            @error('login_id')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            @else
                            <input type="text" class="form-control" value="{{ $registration->login_id ?? '—' }}" readonly>
                            @endif
                        </div>
                    </div>
                </div>

                {{-- ── Employment Details ───────────────────────────── --}}
                <div class="hrms-card p-4 mb-4">
                    <h6 class="fw-semibold mb-3 text-muted text-uppercase" style="font-size:.72rem;letter-spacing:.05em;">
                        Employment Details
                    </h6>
                    <div class="row g-3">

                        @if($branchesEnabled && $branches->isNotEmpty())
                        <div class="col-md-6">
                            <label class="form-label">Branch</label>
                            @if($isEditable)
                            <select name="branch_id" class="form-select @error('branch_id') is-invalid @enderror">
                                <option value="">— None —</option>
                                @foreach($branches as $b)
                                <option value="{{ $b->id }}" {{ old('branch_id', $registration->branch_id) == $b->id ? 'selected' : '' }}>{{ $b->name }}</option>
                                @endforeach
                            </select>
                            @else
                            <input type="text" class="form-control" value="{{ $registration->branch?->name ?? '—' }}" readonly>
                            @endif
                            @error('branch_id')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                        @endif

                        <div class="col-md-6">
                            <label class="form-label">Designation <span class="text-danger">*</span></label>
                            @if($isEditable)
                            <select name="designation_id" class="form-select @error('designation_id') is-invalid @enderror" required>
                                <option value="">— Select —</option>
                                @foreach($designations as $d)
                                <option value="{{ $d->id }}" {{ old('designation_id', $registration->designation_id) == $d->id ? 'selected' : '' }}>{{ $d->name }}</option>
                                @endforeach
                            </select>
                            @else
                            <input type="text" class="form-control" value="{{ $registration->designation?->name ?? '—' }}" readonly>
                            @endif
                            @error('designation_id')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>

                        <div class="col-md-6">
                            <label class="form-label">Department</label>
                            @if($isEditable)
                            <select name="department_id" class="form-select @error('department_id') is-invalid @enderror">
                                <option value="">— None —</option>
                                @foreach($departments as $d)
                                <option value="{{ $d->id }}" {{ old('department_id', $registration->department_id) == $d->id ? 'selected' : '' }}>{{ $d->name }}</option>
                                @endforeach
                            </select>
                            @else
                            <input type="text" class="form-control" value="{{ $registration->department?->name ?? '—' }}" readonly>
                            @endif
                            @error('department_id')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>

                        <div class="col-md-6">
                            <label class="form-label">Shift</label>
                            @if($isEditable)
                            <select name="shift_id" class="form-select @error('shift_id') is-invalid @enderror">
                                <option value="">— None —</option>
                                @foreach($shifts as $s)
                                <option value="{{ $s->id }}" {{ old('shift_id', $registration->shift_id) == $s->id ? 'selected' : '' }}>{{ $s->name }}</option>
                                @endforeach
                            </select>
                            @else
                            <input type="text" class="form-control" value="{{ $registration->shift?->name ?? '—' }}" readonly>
                            @endif
                            @error('shift_id')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>

                        {{-- ── Weekly Off ──────────────────────────────────── --}}
                        <div class="col-12">
                            @php
                                $approvedDays = old('weekly_off_days', $registration->weekly_off_days ?? []);
                                $requestedDays = $registration->weekly_off_days ?? [];
                                $weeklyOffNote = $registration->weekly_off_note;
                            @endphp

                            <div class="border rounded overflow-hidden">
                                {{-- Header --}}
                                <div class="px-3 py-2 d-flex align-items-center gap-2"
                                     style="background:#f8f9fa;border-bottom:1px solid #dee2e6;">
                                    <i class="bi bi-calendar2-week text-primary"></i>
                                    <span class="fw-semibold" style="font-size:.875rem;">Weekly Off</span>
                                </div>

                                <div class="p-3">
                                    {{-- Employee's original request (read-only, always visible) --}}
                                    @if($requestedDays || $weeklyOffNote)
                                    <div class="mb-3 p-2 rounded" style="background:#f0f7ff;border:1px solid #cce4f7;">
                                        <p class="mb-1 fw-semibold" style="font-size:.78rem;color:#0d6efd;text-transform:uppercase;letter-spacing:.04em;">
                                            <i class="bi bi-person me-1"></i>Applicant's Request
                                        </p>
                                        @if($requestedDays)
                                            <div class="d-flex flex-wrap gap-1 mb-1">
                                                @foreach($requestedDays as $day)
                                                    <span class="badge bg-primary-subtle text-primary">{{ ucfirst($day) }}</span>
                                                @endforeach
                                            </div>
                                        @else
                                            <span class="text-muted" style="font-size:.85rem;">No specific day requested</span>
                                        @endif
                                        @if($weeklyOffNote)
                                            <p class="mb-0 mt-1 fst-italic" style="font-size:.82rem;color:#495057;">
                                                "{{ $weeklyOffNote }}"
                                            </p>
                                        @endif
                                    </div>
                                    @endif

                                    {{-- HR's approval section --}}
                                    <label class="form-label mb-2" style="font-size:.85rem;">
                                        <i class="bi bi-check2-circle me-1 text-success"></i>
                                        @if($isEditable)
                                            <strong>Approved Weekly Off Days</strong>
                                            <span class="text-muted fw-normal">(you can change the applicant's request)</span>
                                        @else
                                            <strong>Approved Weekly Off Days</strong>
                                        @endif
                                    </label>

                                    @if($isEditable)
                                        <div class="d-flex flex-wrap gap-2 mb-2">
                                            @foreach(['sunday','monday','tuesday','wednesday','thursday','friday','saturday'] as $day)
                                                <label class="border rounded px-3 py-2 d-flex align-items-center gap-2"
                                                       style="cursor:pointer;font-size:.875rem;">
                                                    <input type="checkbox"
                                                           name="weekly_off_days[]"
                                                           value="{{ $day }}"
                                                           @checked(in_array($day, $approvedDays, true))>
                                                    {{ ucfirst($day) }}
                                                </label>
                                            @endforeach
                                        </div>
                                        @error('weekly_off_days')
                                            <div class="text-danger small mb-2">{{ $message }}</div>
                                        @enderror

                                        {{-- HR note about weekly off --}}
                                        <label class="form-label mb-1" style="font-size:.82rem;">HR Note <span class="text-muted">(optional — saved with the weekly off record)</span></label>
                                        <textarea name="weekly_off_note"
                                                  rows="2"
                                                  class="form-control form-control-sm @error('weekly_off_note') is-invalid @enderror"
                                                  placeholder="e.g. Approved as requested / Changed to Saturday per company policy…"
                                                  maxlength="500">{{ old('weekly_off_note', $registration->weekly_off_note) }}</textarea>
                                        @error('weekly_off_note')
                                            <div class="invalid-feedback">{{ $message }}</div>
                                        @enderror
                                    @else
                                        {{-- Read-only display --}}
                                        <div>
                                            @if($approvedDays)
                                                <div class="d-flex flex-wrap gap-1">
                                                    @foreach($approvedDays as $day)
                                                        <span class="badge bg-success-subtle text-success">{{ ucfirst($day) }}</span>
                                                    @endforeach
                                                </div>
                                            @else
                                                <span class="text-muted" style="font-size:.875rem;">—</span>
                                            @endif
                                            @if($weeklyOffNote)
                                                <p class="mb-0 mt-1 text-muted fst-italic" style="font-size:.82rem;">"{{ $weeklyOffNote }}"</p>
                                            @endif
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <label class="form-label">Employment Type <span class="text-danger">*</span></label>
                            @if($isEditable)
                            <select name="employment_type" class="form-select @error('employment_type') is-invalid @enderror" required>
                                <option value="full_time" {{ old('employment_type', $registration->employment_type) === 'full_time' ? 'selected' : '' }}>Full Time</option>
                                <option value="part_time" {{ old('employment_type', $registration->employment_type) === 'part_time' ? 'selected' : '' }}>Part Time</option>
                                <option value="contract"  {{ old('employment_type', $registration->employment_type) === 'contract'  ? 'selected' : '' }}>Contract</option>
                            </select>
                            @else
                            <input type="text" class="form-control" value="{{ str_replace('_', ' ', ucfirst($registration->employment_type)) }}" readonly>
                            @endif
                            @error('employment_type')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>

                        <div class="col-md-6">
                            <label class="form-label">Join Date <span class="text-danger">*</span></label>
                            <input type="date" name="join_date"
                                   class="form-control @error('join_date') is-invalid @enderror"
                                   value="{{ old('join_date', $registration->join_date?->format('Y-m-d')) }}"
                                   {{ $isEditable ? '' : 'readonly' }} required>
                            @error('join_date')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>

                        <div class="col-md-6">
                            <label class="form-label">Base Salary <span class="text-danger">*</span></label>
                            <div class="input-group">
                                <span class="input-group-text">{{ setting('currency_symbol', '$') }}</span>
                                <input type="number" name="base_salary" step="0.01" min="0"
                                       class="form-control @error('base_salary') is-invalid @enderror"
                                       value="{{ old('base_salary', $registration->base_salary) }}"
                                       {{ $isEditable ? '' : 'readonly' }} required>
                            </div>
                            @error('base_salary')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>

                    </div>
                </div>

                @if($isEditable)
                <div class="d-flex gap-3 mb-4">
                    <button type="submit" class="btn btn-outline-secondary">
                        <i class="bi bi-floppy me-1"></i> Save Changes
                    </button>
                </div>
                @endif

            </div>

            {{-- ── Right sidebar: actions ─────────────────────────── --}}
            <div class="col-lg-4">

                {{-- Status & Actions --}}
                <div class="hrms-card p-4 mb-4">
                    <h6 class="fw-semibold mb-3" style="font-size:.82rem;text-transform:uppercase;letter-spacing:.05em;color:#6c757d;">
                        Review Actions
                    </h6>

                    @php
                        $sc = match($registration->status) {
                            'pending'              => 'bg-warning-subtle text-warning border-warning',
                            'approved'             => 'bg-success-subtle text-success border-success',
                            'rejected'             => 'bg-danger-subtle text-danger border-danger',
                            'correction_required'  => 'bg-orange-subtle text-warning border-warning',
                            default                => 'bg-secondary-subtle text-secondary',
                        };
                        $statusLabel = match($registration->status) {
                            'correction_required' => 'Correction Required',
                            default => ucfirst($registration->status),
                        };
                    @endphp
                    <div class="badge {{ $sc }} fs-6 mb-4 px-3 py-2 d-block text-center border">
                        {{ $statusLabel }}
                    </div>

                    @if($canApprove)
                    {{--
                        PRIMARY action: saves all HR edits from the form AND
                        creates the employee account in one atomic transaction.
                        This is the recommended button for normal workflow.
                    --}}
                    <button type="button" class="btn btn-success w-100 mb-2" id="btnSaveAndApprove">
                        <i class="bi bi-check-circle-fill me-2"></i>Save &amp; Approve
                    </button>

                    {{-- Secondary: approve with current DB data, no changes saved --}}
                    <form method="POST" action="{{ route('registrations.approve', $registration) }}" class="mb-2" id="formQuickApprove">
                        @csrf
                        <button type="submit" class="btn btn-outline-success w-100">
                            <i class="bi bi-check-circle me-2"></i>Approve (no changes)
                        </button>
                    </form>
                    <hr class="my-2">

                    <button type="button" class="btn btn-outline-warning w-100 mb-2" id="btnRequestCorrection">
                        <i class="bi bi-pencil-square me-2"></i>Request Correction
                    </button>

                    <button type="button" class="btn btn-outline-danger w-100" id="btnReject">
                        <i class="bi bi-x-circle me-2"></i>Reject Registration
                    </button>
                    @endif
                </div>

                {{-- Invitation info --}}
                <div class="hrms-card p-4 mb-4">
                    <h6 class="fw-semibold mb-3" style="font-size:.82rem;text-transform:uppercase;letter-spacing:.05em;color:#6c757d;">
                        Invitation Details
                    </h6>
                    <dl class="mb-0" style="font-size:.82rem;">
                        <dt class="text-muted fw-normal">Link Generated By</dt>
                        <dd class="fw-semibold mb-2">
                            <i class="bi bi-person-badge text-primary me-1" style="font-size:.75rem;"></i>
                            {{ $registration->invitation?->creator?->name ?? '—' }}
                        </dd>
                        <dt class="text-muted fw-normal">Invitation Note</dt>
                        <dd class="mb-2">{{ $registration->invitation?->note ?: '—' }}</dd>
                        <dt class="text-muted fw-normal">Link Capacity</dt>
                        <dd class="mb-2">
                            @php $inv = $registration->invitation; @endphp
                            @if($inv)
                                {{ $inv->uses_count }}
                                / {{ $inv->max_uses === null ? '∞ (unlimited)' : $inv->max_uses }}
                                uses
                            @else
                                —
                            @endif
                        </dd>
                        <dt class="text-muted fw-normal">Link Status</dt>
                        <dd class="mb-2">
                            @if($inv)
                            @php
                                $ls = $inv->status;
                                $lc = match($ls) {
                                    'active'    => 'bg-success-subtle text-success',
                                    'exhausted' => 'bg-info-subtle text-info',
                                    'revoked'   => 'bg-danger-subtle text-danger',
                                    default     => 'bg-warning-subtle text-warning',
                                };
                            @endphp
                            <span class="badge {{ $lc }}">{{ ucfirst($ls) }}</span>
                            @else —
                            @endif
                        </dd>
                        <dt class="text-muted fw-normal">Link Expires</dt>
                        <dd class="mb-0">{{ $registration->invitation?->expires_at->format('d M Y H:i') ?? '—' }}</dd>
                    </dl>
                </div>

            </div>
        </div>

    </form>

    {{-- ── Activity Log Timeline ─────────────────────────────────── --}}
    @if($registration->activityLogs->isNotEmpty())
    <div class="hrms-card p-4 mt-2 mb-4">
        <h6 class="fw-semibold mb-4 text-muted text-uppercase" style="font-size:.72rem;letter-spacing:.05em;">
            <i class="bi bi-clock-history me-1"></i>Activity Log
        </h6>
        <div class="position-relative" style="padding-left: 2rem;">
            {{-- vertical line --}}
            <div style="position:absolute;left:.65rem;top:0;bottom:0;width:2px;background:#e9ecef;"></div>

            @foreach($registration->activityLogs as $log)
            @php
                $color = $log->action_color;
                $dotBg = match($color) {
                    'primary'   => '#0d6efd',
                    'info'      => '#0dcaf0',
                    'success'   => '#198754',
                    'danger'    => '#dc3545',
                    'warning'   => '#ffc107',
                    default     => '#6c757d',
                };
            @endphp
            <div class="d-flex gap-3 mb-4 position-relative">
                {{-- dot --}}
                <div style="position:absolute;left:-1.63rem;width:18px;height:18px;border-radius:50%;background:{{ $dotBg }};border:3px solid #fff;box-shadow:0 0 0 2px {{ $dotBg }}44;top:2px;flex-shrink:0;"></div>
                <div class="flex-grow-1">
                    <div class="d-flex align-items-center gap-2 flex-wrap">
                        <span class="badge bg-{{ $color }}-subtle text-{{ $color }} border border-{{ $color }}-subtle" style="font-size:.72rem;">
                            {{ $log->action_label }}
                        </span>
                        <span class="text-muted" style="font-size:.78rem;">
                            {{ $log->created_at->format('d M Y H:i') }}
                        </span>
                    </div>
                    <div style="font-size:.82rem;" class="mt-1">
                        <span class="fw-semibold">{{ $log->actor?->name ?? 'Applicant' }}</span>
                        @if($log->note)
                        <span class="text-muted ms-1">— {{ $log->note }}</span>
                        @endif
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
    @endif

    {{-- ── Reject Modal ──────────────────────────────────────────── --}}
    @if($canApprove)
    <div class="modal fade" id="rejectModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-semibold text-danger">Reject Registration</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <form method="POST" action="{{ route('registrations.reject', $registration) }}">
                    @csrf
                    <div class="modal-body">
                        <p style="font-size:.9rem;" class="text-muted">
                            Rejecting will prevent this applicant from logging in. Please provide a reason.
                        </p>
                        <div class="mb-3">
                            <label class="form-label">Rejection Note <span class="text-danger">*</span></label>
                            <textarea name="rejection_note" class="form-control @error('rejection_note') is-invalid @enderror"
                                      rows="3" required maxlength="500"
                                      placeholder="Reason for rejection…">{{ old('rejection_note') }}</textarea>
                            @error('rejection_note')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-danger">Confirm Rejection</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {{-- ── Correction Request Modal ──────────────────────────────── --}}
    <div class="modal fade" id="correctionModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-semibold text-warning">Request Correction</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <form method="POST" action="{{ route('registrations.correction', $registration) }}">
                    @csrf
                    <div class="modal-body">
                        <p style="font-size:.9rem;" class="text-muted">
                            Describe what the applicant needs to fix. They will be notified.
                        </p>
                        <div class="mb-3">
                            <label class="form-label">Correction Note <span class="text-danger">*</span></label>
                            <textarea name="correction_note" class="form-control @error('correction_note') is-invalid @enderror"
                                      rows="4" required maxlength="1000"
                                      placeholder="Describe what needs to be corrected…">{{ old('correction_note') }}</textarea>
                            @error('correction_note')<div class="invalid-feedback">{{ $message }}</div>@enderror
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-warning">Send Correction Request</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    @push('scripts')
    <script>
    document.addEventListener('DOMContentLoaded', function () {

        // ── Modals ─────────────────────────────────────────────────────
        const rejectEl     = document.getElementById('rejectModal');
        const correctionEl = document.getElementById('correctionModal');
        const rejectModal     = rejectEl     ? new bootstrap.Modal(rejectEl)     : null;
        const correctionModal = correctionEl ? new bootstrap.Modal(correctionEl) : null;

        document.getElementById('btnReject')?.addEventListener('click', () => rejectModal?.show());
        document.getElementById('btnRequestCorrection')?.addEventListener('click', () => correctionModal?.show());

        // ── Save & Approve ─────────────────────────────────────────────
        // When clicked, we switch the form's action to the save-and-approve
        // endpoint and remove the PATCH method override (it must be a POST).
        document.getElementById('btnSaveAndApprove')?.addEventListener('click', function () {
            const form = document.getElementById('mainRegistrationForm');
            if (!form) return;

            if (! confirm('Save all current edits and approve this registration? An employee account will be created immediately.')) {
                return;
            }

            // Point the form at the combined save-and-approve endpoint
            form.action = '{{ route('registrations.save-and-approve', $registration) }}';

            // The combined endpoint is a plain POST — remove the PATCH spoofing input
            const methodInput = form.querySelector('input[name="_method"]');
            if (methodInput) methodInput.remove();

            form.submit();
        });

        // ── Photo preview ──────────────────────────────────────────────
        window.previewUpdatePhoto = function (input) {
            if (!input.files[0]) return;
            const reader = new FileReader();
            reader.onload = function (e) {
                const img = document.querySelector('.hrms-card img[alt="Profile photo"]');
                if (img) {
                    img.src = e.target.result;
                } else {
                    const placeholder = document.querySelector('.hrms-card div[style*="border-radius:50%"]');
                    if (placeholder) {
                        const newImg = document.createElement('img');
                        newImg.src = e.target.result;
                        newImg.alt = 'Profile photo';
                        newImg.style.cssText = 'width:90px;height:90px;border-radius:50%;object-fit:cover;border:3px solid #e9ecef;';
                        placeholder.replaceWith(newImg);
                    }
                }
            };
            reader.readAsDataURL(input.files[0]);
        };

    }); // end DOMContentLoaded
    </script>
    @endpush
    @endif

</x-app-layout>
